apiVersion: v1
name: telescopes
home: https://banzaicloud.com
sources:
  - https://github.com/banzaicloud/banzai-charts
version: 0.2.0
appVersion: 0.5.3
description: A Telescopes Helm chart for Kubernetes
keywords:
- spot
- aws
- telescopes
- lifecycle
maintainers:
- name: Banzai Cloud
  email: info@banzaicloud.com

icon: https://banzaicloud.com/img/banzai-cloud-logo.svg

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
# type: application