[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "github.com/gin-gonic/gin"
  branch = "master"

[[constraint]]
  name = "github.com/banzaicloud/cloudinfo"
  revision = "073895e77701946ed97c7d5a1fcfbdf1d7d53376"

[[constraint]]
  name = "github.com/gin-contrib/cors"
  version = "v1.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.3.0"

[[constraint]]
  name = "github.com/banzaicloud/bank-vaults"
  version = "0.2.26"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "v1.3.1"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "v1.0.3"

[[constraint]]
  name = "github.com/banzaicloud/go-gin-prometheus"
  revision = "fa3b20bd0ba938372f83549aa82ba0d247ac7e7a"

[[constraint]]
  name = "github.com/goph/emperror"
  version = "0.16.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/moogar0880/problems"
  version = "0.1.0"

[[override]]
  name = "github.com/gin-gonic/gin"
  version = "v1.3.0"

[[constraint]]
  name = "github.com/goph/logur"
  version = "0.10.0"

[[constraint]]
  name = "github.com/gofrs/uuid"
  version = "3.2.0"

[[constraint]]
  name = "github.com/go-openapi/runtime"
  version = "v0.18.0"