[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "github.com/gin-gonic/gin"
  branch = "master"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/banzaicloud/productinfo"
  branch = "master"

[[constraint]]
  name = "github.com/gin-contrib/cors"
  version = "1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/banzaicloud/bank-vaults"
  version = "0.2.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/banzaicloud/go-gin-prometheus"
